"use client";

import localFont from "next/font/local";
import "./globals.css";
import { createTheme, NextUIProvider } from '@nextui-org/react';
import { useEffect, useState } from 'react';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

/*export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        {children}
      </body>
    </html>
  );
}*/


export default function RootLayout({ children }) {
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    const isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
    setDarkMode(isDarkMode);
  }, []);

  const theme = {
    type: darkMode ? 'dark' : 'light',  
    theme: {
      colors: {
        background: darkMode ? '#0a0a0a' : '#ffffff',
        foreground: darkMode ? '#ededed' : '#171717',
      },
    },
  };

  return (
    <html lang="en">
      <body>
        <NextUIProvider theme={theme}>
          {children}  
        </NextUIProvider>
      </body>
    </html>
  );
}

